'once_cycle_policy': False
#     'batch_size': 224,
'batch_size': 20
'min_epochs': 70
'max_epochs': 150
#'transform_resize': 48
'transform_resize': 224
#'model_name': "wide_resnet50_2"
'model_name': "liu"
'pretrained': True
'optimizer_name': 'SGD' # not used atm
'data_dir': "ntu/ntu_120_CaetanoOrientation/cross_subject"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models/efficientb2"
