'learning_rate': 0.03
'momentum': 0.9
'weight_decay' : 0.0
'amp_level': "O2"
'use_amp': True
'gpus': -1
'once_cycle_policy': False
#     'batch_size': 224,
'batch_size': 100
'min_epochs': 100
'max_epochs': 150
'transform_resize': 64
'model_name': "wide_resnet50_2"
#     'model_name': "custom",
'pretrained': True
'optimizer_name': 'SGD' # not used atm
#'data_dir': "ntu/ntu_120_CaetanoMagnitude/cross_setup"
'data_dir': "ntu/ntu_120_CaetanoMagnitude/cross_setup"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models"
