'learning_rate': 0.05
'momentum': 0.3
'weight_decay' : 0.0
'once_cycle_policy': False
'batch_size': 100
#     'batch_size': 224,
'min_epochs': 200
'max_epochs': 500
'transform_resize': 224
'model_name': "wide_resnet50_2"
#     'model_name': "custom",
'pretrained': True
'optimizer_name': 'SGD' # not used atm
'data_dir': "ntu/ntu_60_no_border/cross_subject"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models/transform_300"
