'learning_rate': 0.03
'momentum': 0.9
'weight_decay' : 0.0
'amp_level': "O2"
'use_amp': True
'gpus': -1
'once_cycle_policy': False
#     'batch_size': 224,
'batch_size': 70
'min_epochs': 70
'max_epochs': 150
'transform_resize': 224
'model_name': "resnet18"
#     'model_name': "custom",
'pretrained': True
'optimizer_name': 'SGD' # not used atm
'data_dir': "utdmhad/UTDMHAD_inertial_no_border"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models/iros_final/224_transform/"
