'once_cycle_policy': False
'batch_size': 100
'min_epochs': 70
'max_epochs': 150
'transform_resize': 224
#'model_name': "resnet18"
'model_name': "resnet50"
#     'model_name': "custom",
'pretrained': True
'optimizer_name': 'SGD' # not used atm
'data_dir': "utdmhad/UTDMHAD_fusedapproach_id010_0.2_size_1_no_attention_filter_0.2"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models/iros_final/224_transform/"
